services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    # environment:
    #   - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
    #   - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
    #   - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    #   - DB_TYPE=${N8N_DB_TYPE}
    #   - DB_POSTGRESDB_HOST=${N8N_DB_POSTGRESDB_HOST}
    #   - DB_POSTGRESDB_PORT=${N8N_DB_POSTGRESDB_PORT}
    #   - DB_POSTGRESDB_DATABASE=${N8N_DB_POSTGRESDB_DATABASE}
    #   - DB_POSTGRESDB_USER=${N8N_DB_POSTGRESDB_USER}
    #   - DB_POSTGRESDB_PASSWORD=${N8N_DB_POSTGRESDB_PASSWORD}
    #   - NODE_FUNCTION_ALLOW_EXTERNAL=${N8N_NODE_FUNCTION_ALLOW_EXTERNAL}
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: