version: '3.9' # Or a version compatible with your Docker installation

services:
  api:
    build: . # Assumes Dockerfile is in the root directory
    container_name: stahla_api
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./app:/app # Mount the app directory for live code changes
      - ./assets:/app/assets # Mount assets if needed by the app
      - ./info:/app/info # Mount info if needed by the app
      - ./docs:/static_docs # Mount the docs directory into the container
    env_file:
      - .env # Load environment variables from .env file
    # Command to run the FastAPI app using Uvicorn with reload
    # Adjust 'app.main:app' if your FastAPI app instance is located differently
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

# You can add other services like databases, Redis, etc. here if needed
# Example for a PostgreSQL database:
#  db:
#    image: postgres:15
#    container_name: stahla_db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: stahla_db
#    ports:
#      - "5432:5432"

# volumes:
#  postgres_data: # Define the volume for PostgreSQL data persistence
