# Fly.io configuration for Nginx reverse proxy
app = "stahla"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[env]
  API_HOST = "stahla-api.internal"
  API_PORT = "8000"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
