# Fly.io configuration for complete Stahla application
# Single app with multiple processes: MongoDB, Redis, FastAPI, and Nginx
app = "stahla"
primary_region = "sjc"

[build]
dockerfile = "../Dockerfile"

[deploy]
strategy = "immediate"
release_command = "/app/startup.sh"

[env]
# Basic runtime configuration - most secrets are set via flyctl secrets
PORT = "8000"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "connections"
hard_limit = 100
soft_limit = 80

[[http_service.checks]]
interval = "15s"
grace_period = "10s"
method = "GET"
path = "/health"
protocol = "http"
timeout = "5s"

# Multiple volumes for different services
[mounts]
source = "stahla_data"
destination = "/data"

[[vm]]
cpu_kind = "shared"
cpus = 2
memory_mb = 2048

# Define multiple processes that run together
[processes]
# Main application process that manages all services
app = "/app/init.sh --supervisor"
