# Fly.io configuration for Redis service
app = "stahla-redis"
primary_region = "sjc"

[build]
  image = "redis:7-alpine"

[http_service]
  internal_port = 6379
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.ports]]
    port = 6379
    handlers = []

[[http_service.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  port = 6379

[mounts]
  source = "stahla_redis_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "redis-server --appendonly yes"
