### Variables
@base_url = http://localhost:8000/api/v1
@auth_token = your_auth_token_here
@content_type = application/json

###
# @name GetErrorLogs
GET {{base_url}}/error-logs/
Content-Type: {{content_type}}
Authorization: Bearer {{auth_token}}

###
# @name GetErrorLogById
GET {{base_url}}/error-logs/your_error_id_here
Content-Type: {{content_type}}
Authorization: Bearer {{auth_token}}

###
# @name DeleteErrorLog
DELETE {{base_url}}/error-logs/your_error_id_here
Content-Type: {{content_type}}
Authorization: Bearer {{auth_token}}
